### ISSUE TITLE
Use remote URL for `--drive-service-account-file-path`

### ISSUE THREAD

**Issue by abusenet** [NyaMisty/fclone#3]
#### The associated forum post URL from `https://forum.rclone.org`
None

#### What is your current rclone version (output from `rclone version`)?
v1.58.0-beta.6180.49effc9a7

#### What problem are you are trying to solve?

Fetch the service account JSON file from a remote URL instead of local file. Should support basic authentication as well, i.e. https://username:password@example.com/accounts.

That remote URL should return the SA JSON in response.

#### How do you think rclone should be changed to solve that?
It should be very straight forward to use a built-in HTTP client to fetch the SA when the parameter is a URL.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by NyaMisty** [comment]
The HTTP interface does not offer a good way to list all files in a folder. Also once an operation started, the SA pool won't be updated, so using HTTP to store SA is totally pointless currently.
